

SET IDENTITY_INSERT [Countries] ON
GO

INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (0, 0, N'  ', N'   ', N'', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (1, 4, N'AF', N'AFG', N'Afghanistan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (2, 8, N'AL', N'ALB', N'Albania', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (3, 12, N'DZ', N'DZA', N'Algeria', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (4, 16, N'AS', N'ASM', N'American Samoa', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (5, 20, N'AD', N'AND', N'Andorra', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (6, 24, N'AO', N'AGO', N'Angola', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (7, 660, N'AI', N'AIA', N'Anguilla', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (8, 10, N'AQ', N'ATA', N'Antarctica', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (9, 28, N'AG', N'ATG', N'Antigua and Barbuda', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (10, 32, N'AR', N'ARG', N'Argentina', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (11, 51, N'AM', N'ARM', N'Armenia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (12, 533, N'AW', N'ABW', N'Aruba', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (13, NULL, N'--', N'-- ', N'Ashmore and Cartier', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (14, 36, N'AU', N'AUS', N'Australia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (15, 40, N'AT', N'AUT', N'Austria', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (16, 31, N'AZ', N'AZE', N'Azerbaijan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (17, 44, N'BS', N'BHS', N'The Bahamas', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (18, 48, N'BH', N'BHR', N'Bahrain', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (19, NULL, N'--', N'-- ', N'Baker Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (20, 50, N'BD', N'BGD', N'Bangladesh', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (21, 52, N'BB', N'BRB', N'Barbados', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (22, NULL, N'--', N'-- ', N'Bassas da India', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (23, 112, N'BY', N'BLR', N'Belarus', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (24, 56, N'BE', N'BEL', N'Belgium', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (25, 84, N'BZ', N'BLZ', N'Belize', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (26, 204, N'BJ', N'BEN', N'Benin', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (27, 60, N'BM', N'BMU', N'Bermuda', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (28, 64, N'BT', N'BTN', N'Bhutan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (29, 68, N'BO', N'BOL', N'Bolivia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (30, 70, N'BA', N'BIH', N'Bosnia and Herzegovina', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (31, 72, N'BW', N'BWA', N'Botswana', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (32, 74, N'BV', N'BVT', N'Bouvet Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (33, 76, N'BR', N'BRA', N'Brazil', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (34, 86, N'IO', N'IOT', N'British Indian Ocean Territory', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (35, 92, N'VG', N'VGB', N'British Virgin Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (36, 96, N'BN', N'BRN', N'Brunei Darussalam', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (37, 100, N'BG', N'BGR', N'Bulgaria', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (38, 854, N'BF', N'BFA', N'Burkina Faso', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (39, 104, N'MM', N'MMR', N'Burma', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (40, 108, N'BI', N'BDI', N'Burundi', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (41, 116, N'KH', N'KHM', N'Cambodia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (42, 120, N'CM', N'CMR', N'Cameroon', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (43, 124, N'CA', N'CAN', N'Canada', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (44, 132, N'CV', N'CPV', N'Cape Verde', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (45, 136, N'KY', N'CYM', N'Cayman Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (46, 140, N'CF', N'CAF', N'Central African Republic', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (47, 148, N'TD', N'TCD', N'Chad', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (48, 152, N'CL', N'CHL', N'Chile', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (49, 156, N'CN', N'CHN', N'China', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (50, 162, N'CX', N'CXR', N'Christmas Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (51, NULL, N'--', N'-- ', N'Clipperton Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (52, 166, N'CC', N'CCK', N'Cocos (Keeling) Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (53, 170, N'CO', N'COL', N'Colombia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (54, 174, N'KM', N'COM', N'Comoros', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (55, 180, N'CD', N'COD', N'Congo, Democratic Republic of the', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (56, 178, N'CG', N'COG', N'Congo, Republic of the', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (57, 184, N'CK', N'COK', N'Cook Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (58, NULL, N'--', N'-- ', N'Coral Sea Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (59, 188, N'CR', N'CRI', N'Costa Rica', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (60, 384, N'CI', N'CIV', N'Cote d''Ivoire', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (61, 191, N'HR', N'HRV', N'Croatia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (62, 192, N'CU', N'CUB', N'Cuba', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (63, 196, N'CY', N'CYP', N'Cyprus', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (64, 203, N'CZ', N'CZE', N'Czech Republic', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (65, 208, N'DK', N'DNK', N'Denmark', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (66, 262, N'DJ', N'DJI', N'Djibouti', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (67, 212, N'DM', N'DMA', N'Dominica', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (68, 214, N'DO', N'DOM', N'Dominican Republic', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (69, 626, N'TL', N'TLS', N'East Timor', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (70, 218, N'EC', N'ECU', N'Ecuador', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (71, 818, N'EG', N'EGY', N'Egypt', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (72, 222, N'SV', N'SLV', N'El Salvador', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (73, 226, N'GQ', N'GNQ', N'Equatorial Guinea', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (74, 232, N'ER', N'ERI', N'Eritrea', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (75, 233, N'EE', N'EST', N'Estonia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (76, 231, N'ET', N'ETH', N'Ethiopia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (77, NULL, N'--', N'-- ', N'Europa Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (78, 238, N'FK', N'FLK', N'Falkland Islands (Islas Malvinas)', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (79, 234, N'FO', N'FRO', N'Faroe Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (80, 242, N'FJ', N'FJI', N'Fiji', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (81, 246, N'FI', N'FIN', N'Finland', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (82, 250, N'FR', N'FRA', N'France', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (83, NULL, N'--', N'-- ', N'France, Metropolitan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (84, 254, N'GF', N'GUF', N'French Guiana', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (85, 258, N'PF', N'PYF', N'French Polynesia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (86, 260, N'TF', N'ATF', N'French Southern and Antarctic Lands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (87, 266, N'GA', N'GAB', N'Gabon', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (88, 270, N'GM', N'GMB', N'The Gambia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (89, NULL, N'--', N'-- ', N'Gaza Strip', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (90, 268, N'GE', N'GEO', N'Georgia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (91, 276, N'DE', N'DEU', N'Germany', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (92, 288, N'GH', N'GHA', N'Ghana', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (93, 292, N'GI', N'GIB', N'Gibraltar', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (94, NULL, N'--', N'-- ', N'Glorioso Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (95, 300, N'GR', N'GRC', N'Greece', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (96, 304, N'GL', N'GRL', N'Greenland', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (97, 308, N'GD', N'GRD', N'Grenada', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (98, 312, N'GP', N'GLP', N'Guadeloupe', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (99, 316, N'GU', N'GUM', N'Guam', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (100, 320, N'GT', N'GTM', N'Guatemala', NULL)
GO
print 'Processed 100 total records'
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (101, NULL, N'--', N'-- ', N'Guernsey', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (102, 324, N'GN', N'GIN', N'Guinea', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (103, 624, N'GW', N'GNB', N'Guinea-Bissau', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (104, 328, N'GY', N'GUY', N'Guyana', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (105, 332, N'HT', N'HTI', N'Haiti', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (106, 334, N'HM', N'HMD', N'Heard Island and McDonald Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (107, 336, N'VA', N'VAT', N'Holy See (Vatican City)', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (108, 340, N'HN', N'HND', N'Honduras', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (109, 344, N'HK', N'HKG', N'Hong Kong (SAR)', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (110, NULL, N'--', N'-- ', N'Howland Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (111, 348, N'HU', N'HUN', N'Hungary', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (112, 352, N'IS', N'ISL', N'Iceland', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (113, 356, N'IN', N'IND', N'India', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (114, 360, N'ID', N'IDN', N'Indonesia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (115, 364, N'IR', N'IRN', N'Iran', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (116, 368, N'IQ', N'IRQ', N'Iraq', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (117, 372, N'IE', N'IRL', N'Ireland', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (118, 376, N'IL', N'ISR', N'Israel', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (119, 380, N'IT', N'ITA', N'Italy', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (120, 388, N'JM', N'JAM', N'Jamaica', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (121, NULL, N'--', N'-- ', N'Jan Mayen', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (122, 392, N'JP', N'JPN', N'Japan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (123, NULL, N'--', N'-- ', N'Jarvis Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (124, NULL, N'--', N'-- ', N'Jersey', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (125, NULL, N'--', N'-- ', N'Johnston Atoll', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (126, 400, N'JO', N'JOR', N'Jordan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (127, NULL, N'--', N'-- ', N'Juan de Nova Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (128, 398, N'KZ', N'KAZ', N'Kazakhstan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (129, 404, N'KE', N'KEN', N'Kenya', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (130, NULL, N'--', N'-- ', N'Kingman Reef', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (131, 296, N'KI', N'KIR', N'Kiribati', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (132, 408, N'KP', N'PRK', N'Korea, North', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (133, 410, N'KR', N'KOR', N'Korea, South', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (134, 414, N'KW', N'KWT', N'Kuwait', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (135, 417, N'KG', N'KGZ', N'Kyrgyzstan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (136, 418, N'LA', N'LAO', N'Laos', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (137, 428, N'LV', N'LVA', N'Latvia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (138, 422, N'LB', N'LBN', N'Lebanon', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (139, 426, N'LS', N'LSO', N'Lesotho', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (140, 430, N'LR', N'LBR', N'Liberia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (141, 434, N'LY', N'LBY', N'Libya', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (142, 438, N'LI', N'LIE', N'Liechtenstein', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (143, 440, N'LT', N'LTU', N'Lithuania', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (144, 442, N'LU', N'LUX', N'Luxembourg', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (145, 446, N'MO', N'MAC', N'Macao', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (146, 807, N'MK', N'MKD', N'Macedonia, The Former Yugoslav Republic of', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (147, 450, N'MG', N'MDG', N'Madagascar', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (148, 454, N'MW', N'MWI', N'Malawi', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (149, 458, N'MY', N'MYS', N'Malaysia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (150, 462, N'MV', N'MDV', N'Maldives', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (151, 466, N'ML', N'MLI', N'Mali', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (152, 470, N'MT', N'MLT', N'Malta', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (153, NULL, N'--', N'-- ', N'Man, Isle of', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (154, 584, N'MH', N'MHL', N'Marshall Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (155, 474, N'MQ', N'MTQ', N'Martinique', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (156, 478, N'MR', N'MRT', N'Mauritania', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (157, 480, N'MU', N'MUS', N'Mauritius', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (158, 175, N'YT', N'MYT', N'Mayotte', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (159, 484, N'MX', N'MEX', N'Mexico', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (160, 583, N'FM', N'FSM', N'Micronesia, Federated States of', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (161, NULL, N'--', N'-- ', N'Midway Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (162, NULL, N'--', N'-- ', N'Miscellaneous (French)', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (163, 498, N'MD', N'MDA', N'Moldova', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (164, 492, N'MC', N'MCO', N'Monaco', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (165, 496, N'MN', N'MNG', N'Mongolia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (166, NULL, N'--', N'-- ', N'Montenegro', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (167, 500, N'MS', N'MSR', N'Montserrat', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (168, 504, N'MA', N'MAR', N'Morocco', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (169, 508, N'MZ', N'MOZ', N'Mozambique', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (170, NULL, N'--', N'-- ', N'Myanmar', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (171, 516, N'NA', N'NAM', N'Namibia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (172, 520, N'NR', N'NRU', N'Nauru', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (173, NULL, N'--', N'-- ', N'Navassa Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (174, 524, N'NP', N'NPL', N'Nepal', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (175, 528, N'NL', N'NLD', N'Netherlands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (176, 530, N'AN', N'ANT', N'Netherlands Antilles', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (177, 540, N'NC', N'NCL', N'New Caledonia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (178, 554, N'NZ', N'NZL', N'New Zealand', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (179, 558, N'NI', N'NIC', N'Nicaragua', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (180, 562, N'NE', N'NER', N'Niger', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (181, 566, N'NG', N'NGA', N'Nigeria', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (182, 570, N'NU', N'NIU', N'Niue', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (183, 574, N'NF', N'NFK', N'Norfolk Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (184, 580, N'MP', N'MNP', N'Northern Mariana Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (185, 578, N'NO', N'NOR', N'Norway', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (186, 512, N'OM', N'OMN', N'Oman', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (187, 586, N'PK', N'PAK', N'Pakistan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (188, 585, N'PW', N'PLW', N'Palau', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (189, NULL, N'--', N'-- ', N'Palmyra Atoll', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (190, 591, N'PA', N'PAN', N'Panama', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (191, 598, N'PG', N'PNG', N'Papua New Guinea', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (192, NULL, N'--', N'-- ', N'Paracel Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (193, 600, N'PY', N'PRY', N'Paraguay', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (194, 604, N'PE', N'PER', N'Peru', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (195, 608, N'PH', N'PHL', N'Philippines', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (196, 612, N'PN', N'PCN', N'Pitcairn Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (197, 616, N'PL', N'POL', N'Poland', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (198, 620, N'PT', N'PRT', N'Portugal', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (199, 630, N'PR', N'PRI', N'Puerto Rico', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (200, 634, N'QA', N'QAT', N'Qatar', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (201, 638, N'RE', N'REU', N'RÚunion', NULL)
GO
print 'Processed 200 total records'
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (202, 642, N'RO', N'ROU', N'Romania', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (203, 643, N'RU', N'RUS', N'Russia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (204, 646, N'RW', N'RWA', N'Rwanda', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (205, 654, N'SH', N'SHN', N'Saint Helena', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (206, 659, N'KN', N'KNA', N'Saint Kitts and Nevis', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (207, 662, N'LC', N'LCA', N'Saint Lucia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (208, 666, N'PM', N'SPM', N'Saint Pierre and Miquelon', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (209, 670, N'VC', N'VCT', N'Saint Vincent and the Grenadines', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (210, 882, N'WS', N'WSM', N'Samoa', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (211, 674, N'SM', N'SMR', N'San Marino', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (212, 678, N'ST', N'STP', N'SŃo TomÚ and PrÝncipe', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (213, 682, N'SA', N'SAU', N'Saudi Arabia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (214, 686, N'SN', N'SEN', N'Senegal', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (215, NULL, N'--', N'-- ', N'Serbia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (216, NULL, N'--', N'-- ', N'Serbia and Montenegro', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (217, 690, N'SC', N'SYC', N'Seychelles', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (218, 694, N'SL', N'SLE', N'Sierra Leone', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (219, 702, N'SG', N'SGP', N'Singapore', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (220, 703, N'SK', N'SVK', N'Slovakia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (221, 705, N'SI', N'SVN', N'Slovenia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (222, 90, N'SB', N'SLB', N'Solomon Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (223, 706, N'SO', N'SOM', N'Somalia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (224, 710, N'ZA', N'ZAF', N'South Africa', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (225, 239, N'GS', N'SGS', N'South Georgia and the South Sandwich Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (226, 724, N'ES', N'ESP', N'Spain', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (227, NULL, N'--', N'-- ', N'Spratly Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (228, 144, N'LK', N'LKA', N'Sri Lanka', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (229, 736, N'SD', N'SDN', N'Sudan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (230, 740, N'SR', N'SUR', N'Suriname', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (231, 744, N'SJ', N'SJM', N'Svalbard', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (232, 748, N'SZ', N'SWZ', N'Swaziland', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (233, 752, N'SE', N'SWE', N'Sweden', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (234, 756, N'CH', N'CHE', N'Switzerland', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (235, 760, N'SY', N'SYR', N'Syria', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (236, 158, N'TW', N'TWN', N'Taiwan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (237, 762, N'TJ', N'TJK', N'Tajikistan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (238, 834, N'TZ', N'TZA', N'Tanzania', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (239, 764, N'TH', N'THA', N'Thailand', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (240, 768, N'TG', N'TGO', N'Togo', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (241, 772, N'TK', N'TKL', N'Tokelau', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (242, 776, N'TO', N'TON', N'Tonga', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (243, 780, N'TT', N'TTO', N'Trinidad and Tobago', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (244, NULL, N'--', N'-- ', N'Tromelin Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (245, 788, N'TN', N'TUN', N'Tunisia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (246, 792, N'TR', N'TUR', N'Turkey', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (247, 795, N'TM', N'TKM', N'Turkmenistan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (248, 796, N'TC', N'TCA', N'Turks and Caicos Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (249, 798, N'TV', N'TUV', N'Tuvalu', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (250, 800, N'UG', N'UGA', N'Uganda', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (251, 804, N'UA', N'UKR', N'Ukraine', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (252, 784, N'AE', N'ARE', N'United Arab Emirates', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (253, 826, N'GB', N'GBR', N'United Kingdom', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (254, 840, N'US', N'USA', N'United States', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (255, 581, N'UM', N'UMI', N'United States Minor Outlying Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (256, 858, N'UY', N'URY', N'Uruguay', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (257, 860, N'UZ', N'UZB', N'Uzbekistan', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (258, 548, N'VU', N'VUT', N'Vanuatu', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (259, 862, N'VE', N'VEN', N'Venezuela', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (260, 704, N'VN', N'VNM', N'Vietnam', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (261, 850, N'VI', N'VIR', N'Virgin Islands', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (262, NULL, N'--', N'-- ', N'Virgin Islands (UK)', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (263, NULL, N'--', N'-- ', N'Virgin Islands (US)', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (264, NULL, N'--', N'-- ', N'Wake Island', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (265, 876, N'WF', N'WLF', N'Wallis and Futuna', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (266, NULL, N'--', N'-- ', N'West Bank', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (267, 732, N'EH', N'ESH', N'Western Sahara', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (268, NULL, N'--', N'-- ', N'Western Samoa', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (269, NULL, N'--', N'-- ', N'World', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (270, 887, N'YE', N'YEM', N'Yemen', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (271, 891, N'YU', N'YUG', N'Yugoslavia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (272, NULL, N'--', N'-- ', N'Zaire', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (273, 894, N'ZM', N'ZWB', N'Zambia', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (274, 716, N'ZW', N'ZWE', N'Zimbabwe', NULL)
INSERT [dbo].[Countries] ([CountryId], [CountryISOn], [CountryCodeA2], [CountryCodeA3], [CountryName], [rowguid]) VALUES (275, 275, N'PS', N'PSE', N'Palestinian Territory', NULL)

GO
print 'Inserted 276 records'

SET IDENTITY_INSERT [Countries] OFF
GO
